apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: pod-restart-alert
  labels:
    release: prometheus
spec:
  groups:
  - name: pod-restart.rules
    rules:
    - alert: PodRestartingFrequently
      expr: increase(kube_pod_container_status_restarts_total[5m]) > 3
      for: 2m
      labels:
        severity: warning
      annotations:
        summary: "Pod '{{ $labels.pod }}' is restarting frequently"
        description: "Pod '{{ $labels.pod }}' in namespace '{{ $labels.namespace }}' restarted more than 3 times in the last 5 minutes."
